name: Deploy Images to GHCR
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  push-inventory-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Store.InventoryApi'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/willvelida/inventory:latest
          docker push ghcr.io/willvelida/inventory:latest
          
  push-product-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Store.ProductApi'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/willvelida/product:latest
          docker push ghcr.io/willvelida/product:latest
          
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Store'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/willvelida/store:latest
          docker push ghcr.io/willvelida/store:latest
        
